### PR TITLE
Adding support for passing host system AWS_ prefixed variables into runiac container

### PR DESCRIPTION
**Pull request by drmmarsunited**
fix(chore): preventing multiple loops over the same array
feature(AWS_ vars): Adding AWS_ env var support into run container

## Proposed changes

Allowing AWS environment variables to be passed to `runiac` run container, as they were previously restricted to only allow prefixed like: TF_VAR_, ARM_, RUNIAC_.

Common environment variables, as presented in the `entrypoint.sh` in the [AWS hello world starter](https://github.com/runiac/runiac-starter-terraform-aws-hello-world/blob/main/entrypoint.sh), demonstrate the need to allow well-known vars to make their way into the container for use.

## Issues for these changes

[](https://github.com/Optum/runiac/issues/50)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactor (changes to code, which do not change application behavior)

## Checklist

- [X] I have filled out this PR template
- [X] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

## Dependencies and Blockers

I will be making another PR to the AWS hello world repo adding support for the often used AWS_PROFILE env var.

## Relevant Links

[AWS CLI/SDK Support Environment Variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html#envvars-list)

## Further comments

None

### CODE REVIEW

**Comment by drmmarsunited** [comment]
File changes screen kind of tough to read.  Code block now looks like this:

```
for _, env := range cmd2.Env {
			if strings.HasPrefix(env, "TF_VAR_") {
				cmd2.Args = append(cmd2.Args, "-e", env)
			}

			if strings.HasPrefix(env, "ARM_") {
				cmd2.Args = append(cmd2.Args, "-e", env)
			}

			if strings.HasPrefix(env, "RUNIAC_") {
				cmd2.Args = append(cmd2.Args, "-e", env)
			}

			if strings.HasPrefix(env, "AWS_") {
				cmd2.Args = append(cmd2.Args, "-e", env)
			}
		}
```

**Comment by tiny-dancer** [comment]
LGTM, note the CLA

**Comment by drmmarsunited** [comment]
> LGTM, note the CLA

Had to add another email address to my profile.  CLA taken care of now.

**Comment by tiny-dancer** [comment]
@drmmarsunited are you planning any other pull requests or should I cut a release now?

**Comment by drmmarsunited** [comment]
No others planned right here right now. But I'm sure I'll run into more things as I clear each hurdle 🤣

**Comment by tiny-dancer** [comment]
@drmmarsunited released as v0.0.12

**Pull request merged**
