### PR TITLE
Add "new" command for scaffolding projects

### PR DESCRIPTION
**Pull request by mbpolan**
## Proposed changes

This PR adds a `new` command to the CLI. The intent is to quickly scaffold a new runiac project with recommended directory structures. The usage is to run `runiac new` and let the interactive prompts guide the user. Depending on the choices the user makes, the following actions are done:
* A new directory is created with the project name
* `git init` is run if it is installed and the user chooses to use it
* If an example or third-party template is used, the CLI will download that template contents
* If a custom project setup is used, then:
  * A `runiac.yml` is created
  * An `entrypoint.sh` is created
* `runiac init` is executed in the target directory with the correct base Docker image

Output of a custom scaffold using a single set of steps:
```
$ runiac new my-project --template simple --primary-region us-central1 --runner terraform --scm none
🍺 Initialized a new project in directory: my-project.
$ tree -a my-project/
my-project/
├── .git
├── .gitignore
└── step1_initial
├── .runiac
```

Output of a custom scaffold using the `tracks` template:
```
$ runiac new my-project --template tracks --primary-region us-central1 --runner terraform --scm none
🍺 Initialized a new project in directory: my-project.
$ tree -a my-project/
my-project/
├── .git
├── .gitignore
└── tracks
    └── initial
        └── step1_initial
├── .runiac
```

## Issues for these changes

N/A

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [X] I have filled out this PR template
- [X] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

## Dependencies and Blockers

N/A

## Relevant Links

N/A

## Further comments

Much of this `new` command takes inspiration from other various CLIs, including `expo init` and `npm init`. The idea is to give the user either guided prompts to give answers, or command line arguments for powerusers.

runiac-new

### CODE REVIEW

**Comment by tiny-dancer** [comment]
@mbpolan love it. Can you expand a little on how the templates work? For example, could any of the examples be a template?

**Comment by mbpolan** [comment]
@tiny-dancer The idea with these templates is to set up a "starter" project based on the choices the user makes in the prompts, similar to how CRA/expo will initialize a working project for you to start hacking. Right now, this just creates the necessary runiac config files and skeleton directories.

Ideally I'd like to bootstrap these with something like the examples, just haven't settled on an approach yet. I've looked at a few ideas on how to bundle those static files with our CLI. The most promising feature is the [embed package](https://blog.golang.org/go1.16), but that requires Go 1.16. For our version of Go, some possibilities include a packager like [rice](https://github.com/GeertJohan/go.rice). Was planning on this being the next iteration of this feature.

**Comment by tiny-dancer** [comment]
@mbpolan  hugo or gatsby might be a good reference here as well. TL/DR instead of bundling with the cli pull over the wire in a conventionalized way.

that could lead to something like https://www.gatsbyjs.com/starters/?

**Comment by mbpolan** [comment]
@tiny-dancer I've reworked this PR a bit to be more general. I also dropped the command line arguments I originally had in favor of interactive prompts. A user can now run `runiac new` and take one of three options:
1. Use one of our templates: the CLI will download the contents of the appropriate subdirectory from `runiac/examples` (see updated gif)
2. Use a third-party template: the CLI will ask for a URL and download the template as given
3. Use a custom setup: same as the PR was originally; the CLI will prompt the user and build a scaffolded project directory

**Comment by tiny-dancer** [comment]
In conjunction with this pull request will also be looking to have the default container be set to a `latest-kitchen-sink` which has azure, gcp, aws and terraform.  It'll be the simplest to get started and then more advanced users can start specificy their desired container/version/etc.  @mbpolan thoughts?

**Comment by tiny-dancer** [comment]
Also take note runiac.io and docs have a repo of their own: https://github.com/runiac/website

**Comment by mbpolan** [comment]
@tiny-dancer Makes sense to me. I swapped the default container to `alpine-azure-gcloud` for the time being in this PR to account for the various examples we support, but a consolidated "kitchen sink" base image would be a good next step.

**Review by tiny-dancer — APPROVED** [review]

**Pull request merged**
