### PR TITLE
Support deploying ARM templates

### PR DESCRIPTION
**Pull request by mbpolan**
## Proposed changes

Moving runiac to the future. :) I'm opening this PR to kickstart discussions on supporting ARM template deployments.

This is an implementation that allows one to use runiac to manage their Azure resources using standard ARM templates. The scope of this PR is to support a **bare** minimum that we can the build on top of. To that extent, I limited support to deploying to [subscriptions only](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription?tabs=azure-cli), and runiac shells out commands to the Azure CLI itself.

Things I have working so far:
* Deploying templates using the subscription scope
* Preview changes using the `az deployment sub what-if` subcommand
* Deploy changes using the `az deployment sub create` subcommand
* Tear down using a combination of `az deployment sub show` and `az resource delete` commands
* An example that showcases the set up for ARM templates

Implementing `--self-destroy` is a bit tricky since the Azure CLI does not have a native way to deleting resources deployed using a template. Instead, I use the following process:
1. Give each deployment a mostly unique name
2. Deploy the template(s)
3. On destroy, look up the last successful deployment with the same deployment name
4. Extract the outputted resource IDs
5. Run the `az resource delete` command to delete the resource IDs
6. Run the `az deployment sub delete` command to delete the actual deployment metadata

Breaking changes:
* You need to specify a `runner` parameter in `runiac.yml` to determine which delivery tool to use (`terraform` or `arm`)
* Alternatively, you can pass in a `--runner` flag to the CLI

Looking for feedback on the approaches I implemented here.

Sample output:

```bash
$ runiac deploy -c runiac:alpine-azure -e nonprod -a ***** --self-destroy
Adding Step #azure-hello-world#default. Tests Exist: false. Regional Resources Exist: false. Regional Tests Exist: false.
Tracks: Adding default track
(deploy default/default/primary/southcentralus)   Running command: az deployment sub what-if --name runiac-azure-hello-world-default-default-southcentralus --location southcentralus --template-file .temp/main.json --subscription *****.
EnvVars: []
(deploy default/default/primary/southcentralus)   Note: As What-If is currently in preview, the result may contain false positive predictions (noise).
(deploy default/default/primary/southcentralus)   You can help us improve the accuracy of the result by opening an issue here: https://aka.ms/WhatIfIssues.
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)   Resource and property changes are indicated with this symbol:
(deploy default/default/primary/southcentralus)     + Create
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)   The deployment will update the following scopes
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)   Scope: /subscriptions/*****
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)     + resourceGroups/rg-arm [2020-06-01]
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)         apiVersion: "2020-06-01"
(deploy default/default/primary/southcentralus)         id:         "/subscriptions/*****/resourceGroups/rg-arm"
(deploy default/default/primary/southcentralus)         location:   "southcentralus"
(deploy default/default/primary/southcentralus)         name:       "rg-arm"
(deploy default/default/primary/southcentralus)         type:       "Microsoft.Resources/resourceGroups"
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)   Scope: /subscriptions/*****/resourceGroups/rg-arm
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)     + Microsoft.Storage/storageAccounts/st3vhjojeis4c4c [2019-06-01]
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)         apiVersion: "2019-06-01"
(deploy default/default/primary/southcentralus)         id:         "/subscriptions/*****/resourceGroups/rg-arm/providers/Microsoft.Storage/storageAccounts/st3vhjojeis4c4c"
(deploy default/default/primary/southcentralus)         kind:       "StorageV2"
(deploy default/default/primary/southcentralus)         location:   "southcentralus"
(deploy default/default/primary/southcentralus)         name:       "st3vhjojeis4c4c"
(deploy default/default/primary/southcentralus)         sku.name:   "Standard_LRS"
(deploy default/default/primary/southcentralus)         type:       "Microsoft.Storage/storageAccounts"
(deploy default/default/primary/southcentralus)   
(deploy default/default/primary/southcentralus)   Resource changes: 2 to create.
(deploy default/default/primary/southcentralus)   This command is in preview. It may be changed/removed in a future release.
(deploy default/default/primary/southcentralus)   Running command: az deployment sub create --name runiac-azure-hello-world-default-default-southcentralus --location southcentralus --template-file .temp/main.json --subscription *****.
EnvVars: []
(deploy default/default/primary/southcentralus)   {
(deploy default/default/primary/southcentralus)     "id": "/subscriptions/*****/providers/Microsoft.Resources/deployments/runiac-azure-hello-world-default-default-southcentralus",
(deploy default/default/primary/southcentralus)     "location": "southcentralus",
(deploy default/default/primary/southcentralus)     "name": "runiac-azure-hello-world-default-default-southcentralus",
                                                     ...
(deploy default/default/primary/southcentralus)   }
(deploy default)   Track has no regional resources, completing track.
(deploy default)   #azure-hello-world#default#default: SUCCESS: Primary resources applied to southcentralus.  No regional resources for step.
Executing destroy...
(destroy default/default/primary/southcentralus)   Running command: az deployment sub show --name runiac-azure-hello-world-default-default-southcentralus --subscription *****.
EnvVars: []
(destroy default/default/primary/southcentralus)   {
(destroy default/default/primary/southcentralus)     "id": "/subscriptions/*****/providers/Microsoft.Resources/deployments/runiac-azure-hello-world-default-default-southcentralus",
(destroy default/default/primary/southcentralus)     "location": "southcentralus",
                                                     ...
(destroy default/default/primary/southcentralus)   }
(destroy default/default/primary/southcentralus)   Running command: az resource delete --ids /subscriptions/*****/resourceGroups/rg-arm /subscriptions/*****/resourceGroups/rg-arm/providers/Microsoft.Storage/storageAccounts/st3vhjojeis4c4c.
EnvVars: []
(destroy default/default/primary/southcentralus)   [
(destroy default/default/primary/southcentralus)     null,
(destroy default/default/primary/southcentralus)     null
(destroy default/default/primary/southcentralus)   ]
(destroy default/default/primary/southcentralus)   Running command: az deployment sub delete --name runiac-azure-hello-world-default-default-southcentralus --subscription *****.
EnvVars: []
Executed 1/1 steps successfully with 0 test failure(s) across 1 track(s).
```
 
## Issues for these changes

N/A

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (changes to code, which do not change application behavior)

## Checklist

- [X] I have filled out this PR template
- [X] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I have added automated tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (`README.md`, `CHANGELOG.md`, etc. - if appropriate)

## Dependencies and Blockers

N/A

## Relevant Links

* [Deploying to a subscription](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription?tabs=azure-cli)
* [az resource delete](https://docs.microsoft.com/en-us/cli/azure/resource?view=azure-cli-latest#az_resource_delete) command reference
* [what-if](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell) command documentation

## Further comments

N/A

### CODE REVIEW

**Comment by tiny-dancer** [comment]
@mbpolan At a quick overview: looks fantastic, love the start.

Honestly this looks nearly ready to merge in and flag as 'preview' runner from the end user perspective.  Only item coming to mind is ability to pass in runner via cli as an alternative.

We don't have a new `runner` template, but let's get a gif version of your screenshot to place on the readme.

**Comment by mbpolan** [comment]
@tiny-dancer All set, I tweaked a few things since the last review so we can get this merged in.
* Optional CLI `--runner` flag to choose the deployment tool as suggested
* Added a `RunnerPlugin` interface for each plugin to output things like version strings (and possibly some init logic in the future)
  * The ARM runner uses this to print a message that it is still a preview feature
* Readme and related docs updated to reflect all this ^

**Comment by tiny-dancer** [comment]
@mbpolan awesome.

**Comment by mbpolan** [comment]
@tiny-dancer I ran the Terraform examples (among other tests) to validate nothing is broken. The `kitchen-sink` example needed some updates, but otherwise we should be in good shape.

**Pull request merged**
